/**
 * Reading RSS 2.0, RSS 1.0/RDF and Atom, without a dependency.
 *
 * These are three formats that agree on almost nothing except that an item has
 * a title and a link somewhere. The subscription list this was written for
 * contains all three, so all three are handled rather than the one that happens
 * to be commonest.
 *
 * Parsed by regular expression, which is normally the wrong answer for XML and
 * is the right one here. Workers have no DOM parser; the alternative is a
 * dependency in a Worker whose sibling has none; and the failure mode is
 * bounded — a mangled title or a missed item, in a feed that will be read again
 * in an hour. Nothing here is authoritative and nothing is durable enough to
 * be corrupted.
 */

export interface FeedItem {
  /** The feed's own identifier for this entry, or its link as a fallback. */
  guid: string;
  title: string;
  link: string | null;
  /** ISO 8601 if the feed gave anything parseable, else null. */
  publishedAt: string | null;
}

/** Items in document order, which for nearly every feed means newest first. */
export function parseFeed(xml: string): FeedItem[] {
  const blocks = xml.match(/<(item|entry)(?:\s[^>]*)?>[\s\S]*?<\/\1>/g) ?? [];
  const items: FeedItem[] = [];

  for (const block of blocks) {
    const title = text(block, "title") ?? "(untitled)";
    const link = linkOf(block);
    const guid =
      text(block, "guid") ??
      text(block, "id") ??
      link ??
      // Nothing stable to key on. The title is a poor identifier, but it is
      // better than treating every crawl as a fresh arrival.
      title;

    items.push({
      guid: guid.slice(0, 500),
      title: title.slice(0, 500),
      link,
      publishedAt: dateOf(block),
    });
  }

  return items;
}

/** The channel or feed title, for a subscription whose OPML entry lied. */
export function parseFeedTitle(xml: string): string | null {
  // Strip the entries first: their titles are the ones that would otherwise
  // match, since they appear before the closing tag of the channel.
  const head = xml.replace(/<(item|entry)(?:\s[^>]*)?>[\s\S]*?<\/\1>/g, "");
  return text(head, "title");
}

/**
 * Atom puts the address in an attribute and RSS puts it in the element body,
 * and Atom feeds carry several — the self link, alternates, replies, and
 * sometimes an enclosure.
 */
function linkOf(block: string): string | null {
  // Atom: prefer an explicit alternate, then any link with no rel, and never
  // rel="self" or rel="replies" if something else is on offer.
  const hrefs = [...block.matchAll(/<link\b([^>]*)\/?>/g)].map((m) => m[1]);
  const attrOf = (attrs: string, name: string) =>
    new RegExp(`${name}\\s*=\\s*["']([^"']*)["']`).exec(attrs)?.[1] ?? null;

  let fallback: string | null = null;
  for (const attrs of hrefs) {
    const href = attrOf(attrs, "href");
    if (!href) continue;
    const rel = attrOf(attrs, "rel");
    if (rel === "alternate" || rel === null) return decode(href);
    if (!fallback) fallback = decode(href);
  }
  if (fallback) return fallback;

  // RSS 2.0 and RDF: the URL is the element's text.
  const inline = text(block, "link");
  return inline || null;
}

/**
 * The first date-like element that parses, in order of how much a publisher is
 * likely to have meant it.
 *
 * `updated` is last on purpose: an Atom entry edited for a typo three years
 * later is not news, and sorting by it would push it to the top.
 */
function dateOf(block: string): string | null {
  for (const tag of ["pubDate", "published", "dc:date", "date", "updated"]) {
    const raw = text(block, tag);
    if (!raw) continue;
    const parsed = Date.parse(raw);
    if (!Number.isNaN(parsed)) return new Date(parsed).toISOString();
  }
  return null;
}

/**
 * The text of the first matching element, CDATA unwrapped and entities decoded.
 *
 * The tag is matched with an optional namespace prefix, because the same
 * element is `<title>` in RSS, `<title>` in Atom and occasionally
 * `<rss:title>` in a feed generated by something with opinions.
 */
function text(xml: string, tag: string): string | null {
  const name = tag.includes(":") ? tag : `(?:[a-zA-Z0-9]+:)?${tag}`;
  const match = new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)</${name}>`).exec(xml);
  if (!match) return null;

  let value = match[1];
  const cdata = /<!\[CDATA\[([\s\S]*?)\]\]>/.exec(value);
  if (cdata) value = cdata[1];

  return decode(value).replace(/\s+/g, " ").trim() || null;
}

/**
 * Enough entity decoding for titles. Numeric forms first, because a title that
 * has been escaped twice — which is common — decodes `&amp;#8217;` correctly
 * only if the ampersand is handled last.
 */
function decode(value: string): string {
  return value
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(Number(dec)))
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&");
}

// ------------------------------------------------------------------ opml ---

export interface Subscription {
  title: string;
  xmlUrl: string;
  htmlUrl: string | null;
  category: string | null;
}

/**
 * Feeds out of an OPML export, with the folder they sit in as their category.
 *
 * Read once to seed the table and then not consulted again: the crawler learns
 * things the file cannot carry — which feeds have moved, which have been dead
 * for a year — and a re-import must not throw those away.
 */
export function parseOpml(xml: string): Subscription[] {
  const subscriptions: Subscription[] = [];
  const attrOf = (attrs: string, name: string) =>
    new RegExp(`${name}\\s*=\\s*"([^"]*)"`).exec(attrs)?.[1] ?? null;

  // Walked rather than matched, because the category is the enclosing
  // outline's text and a flat search over the file loses that nesting.
  let category: string | null = null;
  for (const match of xml.matchAll(/<outline\b([^>]*?)(\/?)>|<\/outline>/g)) {
    if (match[0] === "</outline>") {
      category = null;
      continue;
    }
    const attrs = match[1];
    const xmlUrl = attrOf(attrs, "xmlUrl");
    const title = attrOf(attrs, "title") ?? attrOf(attrs, "text") ?? "(untitled)";

    if (!xmlUrl) {
      // A container. Self-closing containers exist and hold nothing, so only a
      // real opening tag changes the current folder.
      if (match[2] !== "/") category = decode(title);
      continue;
    }

    subscriptions.push({
      title: decode(title),
      xmlUrl: decode(xmlUrl),
      htmlUrl: attrOf(attrs, "htmlUrl") ? decode(attrOf(attrs, "htmlUrl")!) : null,
      category,
    });
  }

  return subscriptions;
}
